/* Copyright 2025 Tencent Inc.  All rights reserved.

==============================================================================*/
#pragma once

#include <atomic>
#include <limits>
#include <memory>
#include <string>
#include <vector>

#include "configure/environment.h"
#include "pd_v2/public/pd_v2_types.h"
#include "runtime/draft_generator/draft_tokens.h"
#include "runtime/infer_stage.h"
#include "runtime/model_instance.h"
#include "utils/calc_intvec_hash.h"
#include "utils/grammar_matcher.h"
#include "utils/request.h"
#include "utils/status.h"
#include "utils/tensor.h"
#include "utils/waiter.h"

namespace ksana_llm {

// The executor infer request, used for executor runtime only.
class ExecutorInferRequest {
 public:
  ~ExecutorInferRequest();

  void SetReqGroup(const std::vector<std::shared_ptr<ExecutorInferRequest>> &beam_search_infer_group) {
    req_group = beam_search_infer_group;
  }

  // Clear the group of requests.
  void ClearReqGroup() { req_group.clear(); }

  // Notify after request finished.
  void Notify();

  // Notify after step finished.
  void NotifyStep();

  // Get addr ptr of blocks.
  std::vector<void *> GetBlockPtrs(int attn_dp_rank_id);

  // Get this infer request's KV occupied devices.
  std::vector<int> GetKVOccupiedDevices();

  std::vector<int> GetVerifiedTokens();

  std::string PrintKVBlockIds(bool print_details = false) const;

  std::string ToString(bool print_details = false) const;

  friend std::ostream &operator<<(std::ostream &os, const ExecutorInferRequest &req);

 public:
  // The req id of the user's request.
  int64_t req_id;

  // The custom length for the logits output, allowing for a specific size of logits to be generated.
  size_t logits_custom_length = 0;

  size_t sampling_token_num = kStepGenerateTokenNum;

  // build-ahead depth=2：launch 时 placeholder 在 forwarding_tokens 中的全局下标。
  size_t launch_placeholder_offset = std::numeric_limits<size_t>::max();

  // Record the number of tokens sampled in the previous step.
  size_t last_step_token_num = sampling_token_num;

  // The input tokens.
  std::vector<int> input_tokens;

  // Embedding slice used to refit input embedding
  EmbeddingSlice input_refit_embedding;

  // The offset for multimodal rotary position embedding, computed in prefill phase by Python plugin,
  // and used in decode phase.
  int64_t mrotary_embedding_pos_offset = 0;
  int64_t xdrotary_embedding_pos_offset = 0;

  // output_tokens is used during computation. When split fuse is enabled, output_tokens contains only the split
  // part. This variable is dynamically updated based on the current computation phase and may not always represent the
  // complete output.
  std::vector<int> output_tokens;

  // draft token generated by MTP and Trie
  DraftTokens draft_tokens;

  // accepted draft tokens
  std::vector<int> accepted_tokens;

  // draft token num in forwarding_tokens
  size_t forwarding_tokens_draft_num = 0;

  // token generated by model, complete new tokens in a step are (draft_tokens - reject_token_num) + generated_tokens
  std::vector<int> generated_tokens;

  // Store token and their corresponding float probability values.
  std::vector<std::vector<std::pair<int, float>>> logprobs;

  // The key is the request target, which can only be a predefined set of requestable targets {embedding_lookup,
  // layernorm, transformer, logits}.
  std::unordered_map<std::string, TargetDescribe> request_target;

  // The result of request_target.
  std::unordered_map<std::string, PythonTensor> response;

  // The sampling config of this request.
  SamplingConfig sampling_config;

  // The waiter used to notify when request finished.
  std::shared_ptr<Waiter> waiter;

  // The waiter used to notify when step finished.
  std::shared_ptr<Waiter> step_waiter;

  // The waiter used to notify when request aborted..
  std::shared_ptr<Waiter> abort_waiter;

  // Whether the request is finished.
  bool finished;

  // whether the request is aborted.
  std::atomic<bool> aborted{false};

  // Whether the req is mock.
  bool is_mock_req = 0;

  // The final status of this request.
  Status finish_status;

  // Protect parallel access for output token.
  std::mutex output_mutex;

  // grammar matcher (持久化，在 Executor 侧维护)
  std::shared_ptr<GrammarMatcherWrapper> grammar_matcher;

  // Structured generator config for creating generator
  StructuredGeneratorConfig structured_generator_config;

  // Flag indicating whether need to create generator
  bool need_create_generator = false;

  // Structured generator instance (持久化，在 Executor 侧维护)
  std::shared_ptr<StructuredGeneratorInterface> structured_generator;

  std::vector<std::shared_ptr<ExecutorInferRequest>> req_group;

  // The model instance pointer.
  std::shared_ptr<ModelInstance> model_instance;

  std::shared_ptr<BlockAllocatorManager> block_allocator_manager = nullptr;

  // data parallel id of this request.
  uint32_t attn_dp_group_id = 0;

  // This key for kv transformer group.
  std::string kv_comm_group_key;

  // pd_v2: Decode-side KV pool routing for cross-node Prefill→Decode KV
  // RDMA write. Mirrored from engine InferRequest via ScheduleOutput on
  // first transmission only. Empty = non-pd_v2 request, KV-write hook
  // is a no-op for this req.
  std::vector<pd_v2::DecodeTargetLite> pd_v2_decode_targets;
  std::string pd_v2_decode_engine_inference_addr;
  uint32_t pd_v2_decode_attn_dp_group_id = 0;

  /*******************************************************************
   * State info used in generation
   * TODO (robertyuan): Move them into a structure later
   *******************************************************************/
 public:
  // forwarding_tokens contains tokens used in forwarding step. There are two parts:
  // 1. tokens have kv-caches, kv_cached_token_num is the number
  // 2. tokens need to be processed, their kv-caches are generated during computation
  std::vector<int> forwarding_tokens;

  // tokens generated in current step
  std::vector<int> sampling_result_tokens;

  // The intermediate result of beam_search
  std::vector<OutputTuple> beam_search_group;

  // context decode or decode stage.
  InferStage infer_stage = InferStage::kContext;

  // pd_v2: peer Prefill RDMA-wrote K/V for the prompt; trust hook-set
  // forwarding_tokens / kv_cached_token_num and route straight to
  // kPage on first decode forward. Mirrors InferRequest::kv_from_remote;
  // propagated via patch (executor_request_manager.cpp) and through
  // ForwardRequest. See InferRequest's longer comment.
  bool kv_from_remote = false;

  // FastPath / split-fuse 单步语义，决定本步 Executor 是否采样、写 ring、生成 draft。
  ForwardStepKind forward_step_kind = ForwardStepKind::kPrefill;

  // The decode step, 0 for context decode, and then 1, 2, 3...
  int step = 0;

  // The number of tokens for which kv caches have been generated.
  size_t kv_cached_token_num = 0;

  // The kv cache blocks this request used, shared across devices.
  // The key and value are stored in same blocks.
  std::vector<int> kv_cache_blocks;

  // The SWA kv cache blocks for sliding window attention.
  // Mirrors InferRequest::swa_kv_cache_blocks.
  std::vector<int> swa_kv_cache_blocks;

  // Per-block FA global index: swa_kv_cache_block_idx_offsets[i] is the FA block
  // global index corresponding to swa_kv_cache_blocks[i].
  // Mirrors InferRequest::swa_kv_cache_block_idx_offsets.
  std::vector<size_t> swa_kv_cache_block_idx_offsets;

  // The max token number of one block.
  size_t block_token_num;

  // The offset for model forward's logits output.
  size_t logits_offset = 0;

  // The prefix cache tokens number
  int prefix_cache_len = 0;

  // A vector containing pointers to FlexibleCachedCopyTask objects, which represent tasks that involve copying data
  // flexibly between different memory regions.
  std::vector<FlexibleCachedCopyTask> flexible_cached_copy_tasks;

  // The no_repeate ngram sampling map
  NgramDict ngram_dict;

  // Incremental decoded str used in stop strings
  std::string incremental_decoded_str;
};

// The incremental patch for infer request.
class InferRequestPatch {
 public:
  // The req id of the user's request.
  int64_t req_id;

  // The incremental forwarding tokens.
  std::vector<int> delta_forwarding_tokens;

  // The start position of forwarding_tokens.
  size_t forwarding_tokens_offset = 0;

  // draft token num in forwarding_tokens
  size_t forwarding_tokens_draft_num = 0;

  // The number of tokens for which kv caches have been generated.
  size_t kv_cached_token_num = 0;

  // pd_v2: mirrors InferRequest::kv_from_remote on the patch side so
  // executor_request_manager applies the flag. See InferRequest.
  bool kv_from_remote = false;

  // The prefix cache tokens number
  int prefix_cache_len = 0;

  // The kv cache blocks this request used, shared across devices.
  std::vector<int> delta_kv_cache_blocks;
  size_t kv_cache_blocks_offset = 0;

  // The full SWA kv cache blocks; mirrors InferRequest::swa_kv_cache_blocks.
  // Always carries the complete block list (not incremental).
  std::vector<int> swa_kv_cache_blocks;

  // Per-block FA global index: swa_kv_cache_block_idx_offsets[i] is the FA block
  // global index corresponding to swa_kv_cache_blocks[i].
  // Mirrors InferRequest::swa_kv_cache_block_idx_offsets.
  std::vector<size_t> swa_kv_cache_block_idx_offsets;

  // context decode or decode stage.
  InferStage infer_stage = InferStage::kContext;

  // FastPath / split-fuse 单步语义，决定本步 Executor 是否采样、写 ring、生成 draft。
  ForwardStepKind forward_step_kind = ForwardStepKind::kPrefill;

  // The decode step, 0 for context decode, and then 1, 2, 3...
  int step = 0;

  // The number of tokens to sample
  size_t sampling_token_num = kStepGenerateTokenNum;

  // build-ahead depth=2 placeholder 步在 forwarding_tokens 中的全局下标；无 placeholder 时为 SIZE_MAX。
  size_t launch_placeholder_offset = std::numeric_limits<size_t>::max();
};

}  // namespace ksana_llm
